FROM node:alpine

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

COPY ./ ./

CMD [ "npm", "run", "start" ]


# docker build ./ 만 하면 unable to evaluate symlink.. 이러한 에러가 발생한다. 
# 그 이유는 원래는 이미즈를 빌드할 때 해당 디렉토리만 정해주면 Dockerfile을 자동으로 찾아서 빌드하는데
# 현재는 Dockerfile이 없고 Dockerfile.dev 밖에 없으므로 자동으로 올바른 도커 파일을 찾지 못해서 이런 에러가 발생함.

# 해결법 --> docker build -f Dockerfile.dev ./
# -f옵션 : 이미지를 빌드할때 쓰일 도커파일을 임의로 지정해준다.

# 도커환경에서 개발시 로컬에 node_modules는 없어도 되고 COPY ./ ./ 중복으로 카피하기떄문에 지워줘도 된다.

# docker run -it -p 3000:3000 chltjdqh217/docker-react-app 
# -p옵션 : 로컬 포트와 컨테이너 포트 맵핑 해주는 옵션
# -i : 상호 입출력
# -t : tty를 활성화하여 bash 쉘을 사용

# docker run -p 3000:3000 -v /usr/src/app/node_modules -v $(pwd):/usr/src/app <이미지 아이디> --> 소스코드를 바꿔도 이미지를 다시 빌드할 필요가 없다.
# -v /usr/src/app/node_modules --> 첫번째 v. 호스트 디렉토리에 node_modules은 없기에 컨테이너에 맵핑을 하지말라고 하는것
# -v $(pwd):/usr/src/app --> 두번째 v. pwd 경로에 있는 디렉토리 혹은 파일을 컨테이너의 /usr/src/app경로에서 참조